
def get_data_schema():  
    """
    This function returns the data schema for the product sales dataset.
    The schema includes various attributes related to product sales, customer demographics, and supply chain details.
    """
    return  {"data_schema" :[
      { "name": "Product type", "type": "string", "description": "Category of the product (e.g., haircare, skincare)" },
      { "name": "SKU", "type": "string", "description": "Stock Keeping Unit identifier for each product" },
      { "name": "Price", "type": "float", "description": "Price per unit of the product" },
      { "name": "Availability", "type": "int", "description": "Number of units currently available for sale" },
      { "name": "Number of products sold", "type": "int", "description": "Total units sold for the product" },
      { "name": "Revenue generated", "type": "float", "description": "Total revenue generated by product sales" },
      { "name": "Customer demographics", "type": "string", "description": "Customer category (e.g., Female, Male, Non-binary, Unknown)" },
      { "name": "Stock levels", "type": "int", "description": "Current stock level in inventory" },
      { "name": "Lead times", "type": "int", "description": "Time in days from order to delivery" },
      { "name": "Order quantities", "type": "int", "description": "Quantity of product ordered" },
      { "name": "Shipping times", "type": "int", "description": "Time taken to ship the product (in days)" },
      { "name": "Shipping carriers", "type": "string", "description": "Shipping provider name" },
      { "name": "Shipping costs", "type": "float", "description": "Cost incurred for shipping" },
      { "name": "Supplier name", "type": "string", "description": "Name of the product supplier" },
      { "name": "Location", "type": "string", "description": "Geographical origin or supplier location" },
      { "name": "Lead time", "type": "int", "description": "Supplier lead time in days" },
      { "name": "Production volumes", "type": "int", "description": "Quantity of items produced" },
      { "name": "Manufacturing lead time", "type": "int", "description": "Time taken to manufacture the product" },
      { "name": "Manufacturing costs", "type": "float", "description": "Total manufacturing cost" },
      { "name": "Inspection results", "type": "string", "description": "Outcome of quality inspection (e.g., Pass, Fail, Pending)" },
      { "name": "Defect rates", "type": "float", "description": "Percentage of products with defects" },
      { "name": "Transportation modes", "type": "string", "description": "Mode of transport used (e.g., Road, Air, Rail)" },
      { "name": "Routes", "type": "string", "description": "Shipping route designation" },
      { "name": "Costs", "type": "float", "description": "Total cost including production, transport, etc." }
    ]}
  